### ISSUE TITLE
incorrect output for skinvessel example

### ISSUE THREAD

**Issue by ShijieYan** [fangq/mcxcl#45]
<img width="1399" alt="Screenshot 2023-10-05 at 4 42 32 PM" src="https://github.com/fangq/mcxcl/assets/28232429/4ff4fbfd-4487-407b-8228-3eddbf9d399e">

**Comment by fangq** [comment]
@ShijieYan, the bug should be now fixed. Instead of removing the scaling code in `mcx_preprocess()`, I removed the pre-scaling in `mcx_loadconfig` and `mcx_loadjson` in dcdb117.

`mcx_preprocess()` is now the unified preprocessing function shared among mcxcl/mcxlab/pmcxcl to remove duplicated preprocessing codes.
