### ISSUE TITLE
--maxjumpdebug gives MCXCL ERROR(-2):unknown verbose option in unit mcx_utils.c:4003

### ISSUE THREAD

**Issue by naitsok** [fangq/mcxcl#54]
Hello,
Really sorry to bother you that often. Hopefully at some point I will be able to submit pull requests myself.

I now try to get as much photon trajectories as possible out of the simulations.
However when I run `mcxcl -f simulation_2024-06-04_11-20-20.json --debug MP --maxjumpdebug 1e10` I get the following error:
MCXCL ERROR(-2):unknown verbose option in unit mcx_utils.c:4003
I've tried also `-maxjumpdebug 1e10`, the same error.
`maxjumpdebug 1e10` performs the simulation but does not change the number of saved trajectories as MCXCL gives still the warning

WARNING: the saved trajectory positions (-1026007097)   are more than what your have specified (10000000), please use the --maxjumpdebug option to specify a greater number

I used your latest nightly build (dated 04 June 2024) and I again attach the json file I use
[simulation_2024-06-04_11-20-20.json](https://github.com/user-attachments/files/15576036/simulation_2024-06-04_11-20-20.json)

**Comment by fangq** [comment]
thanks for catching this. the missing `--maxjumpdebug` flag has been added.

I also made it possible to accept floating-point numbers, as you wrote, with this flag, but 1e10 will not work. By default, each trajectory position stores 6 floating point numbers, 1e10*6*sizeof(float) = 224GB, which can not be stored on most of commercial GPUs. even it can fit, loading/saving/**properly analyzing** such large amount data will be extremely painful.

I highlighted "properly analyzing" - this is because users often intuitively treat each trajectory equally in their data analysis, but in reality, each segment of the path is associated with weight changes, and they must be accounted properly to generate correct statistics. The trajectory data has been labeled as "debugging purpose only"  since the beginning because it is not recommended for analyses.

one more comment: `cfg.maxjumpdebug` is stored as an unsigned integer internally, so it won't get value higher than 2^31-1.

**Comment by naitsok** [comment]
Thanks for the comprehensive comment, I indeed need to take into account the weight of a photon packet in the analysis.
I've downloaded the latest lightly build, but I still get the same error when running `mcxcl -f simulation_2024-06-04_11-20-20.json --debug MP --maxjumpdebug 1e10`: `MCXCL ERROR(-2):unknown verbose option in unit mcx_utils.c:3999`.
Now it seems that the line number is different.
What am I doing wrong?

**Comment by naitsok** [comment]
I use the Rocky Linux 8.10 on my server with AMD Epyc 32 core CPU (no GPU).
I've downloaded the latest nightly build from here https://mcx.space/nightly/linux64/.
And today when I downloaded, it worked.
Thank you very much for you kind responses!
Now I can also see an issue you pointed out above that the size of trajectories to save is too large. When I specify more than I get the following error.
```
mremap_chunk(): invalid pointer
Aborted (core dumped)
```
or even `Segmentation fault` error.
Probably this is because of too much memory needed although I have here 128 Gb of RAM.
I will may look into your source code at some point to try to get out more trajectories, but for now it seems to work fine with not so many trajectories to retrieve.
Also I will try to switch using partial paths of detected photons rather than using full trajectories.
Thank you once again for very fast answers and patches! I very much appreciate.
