### ISSUE TITLE
A detector's radius gdetpos.w is not squared in photon detection

### ISSUE THREAD

**Issue by naitsok** [fangq/mcxcl#58]
Hello,
The function `finddetector` of `mcx_core.cl` searches for detector in which photon is detected.
In the following line
https://github.com/fangq/mcxcl/blob/2b91626ba444ed4e4cc6765fdcd85d421d37ee04/src/mcx_core.cl#L370
the usual square distance between detector's center and photon coordinates is compared with `gdetpos.w` but not with `gdetpos.w^2`.
Is `gdetpos.w` a detector's radius as stated in documentation or already radius squared?

**Comment by fangq** [comment]
thanks @naitsok for reporting this bug - it has been fixed.

this is a remnant of a the early code where the detector radius is squared right after user input to avoid redundant computation, for example, you can see this in the 2018 release

https://github.com/fangq/mcxcl/blob/v0.8/src/mcx_utils.c#L621

but the pre-computed squared radius has been changed since then.
